package com.Long.dao;

import com.Long.entity.Item;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbggenerated Sun Mar 28 08:48:56 CST 2021
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbggenerated Sun Mar 28 08:48:56 CST 2021
     */
    int insertSelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbggenerated Sun Mar 28 08:48:56 CST 2021
     */
    Item selectByPrimaryKey(Integer id);
    
    // 查询商品列表
    List<Item> listItem();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbggenerated Sun Mar 28 08:48:56 CST 2021
     */
    int updateByPrimaryKeySelective(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_info
     *
     * @mbggenerated Sun Mar 28 08:48:56 CST 2021
     */
    int updateByPrimaryKey(Item record);

    // 增加销量
    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
}