package com.Long.Dao;

import com.Long.entity.ItemStock;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ItemStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Sun Mar 28 08:48:56 CST 2021
     */
    int insert(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Sun Mar 28 08:48:56 CST 2021
     */
    int insertSelective(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Sun Mar 28 08:48:56 CST 2021
     */
    ItemStock selectByPrimaryKey(Integer id);

    // 根据id获取商品库存
    ItemStock selectByItemId(Integer itemId);

    // 减库存
    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Sun Mar 28 08:48:56 CST 2021
     */
    int updateByPrimaryKeySelective(ItemStock record);

}