package com.Long.Dao;

import com.Long.entity.Promo;
import org.springframework.stereotype.Repository;

@Repository
public interface PromoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Sun Mar 28 23:15:01 CST 2021
     */
    int insert(Promo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Sun Mar 28 23:15:01 CST 2021
     */
    int insertSelective(Promo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Sun Mar 28 23:15:01 CST 2021
     */
    Promo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Sun Mar 28 23:15:01 CST 2021
     */
    int updateByPrimaryKeySelective(Promo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbggenerated Sun Mar 28 23:15:01 CST 2021
     */
    int updateByPrimaryKey(Promo record);

    // 根据
    Promo selectByItemId(Integer itemId);
}